#!/bin/sh

if [ -z "$1" ]
then
    echo "usage: nora-wos-view-rec <UT>" >&2
    exit 1
fi
echo "select json from doc where ut='$1';" | sqlite3 /var/lib/nora-wos/db/nora-wos.sqlite3 | /usr/sbin/nora-wos-jsonlint
